config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  mount API => '/api'

  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  # 控制台
  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # 社区
  scope :community, as: 'community' do
    root 'community#index', as: 'index'
    get '/hottest' => 'community#hottest'
    get '/latest' => 'community#latest'
    get '/search' => 'search#index'
    get '/tags/:id' => 'community#tag', as: 'tag'
    get '/articles' => 'community#articles'
    get '/users' => 'community#users'
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get :blog
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#show'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
      post :follow
      post :unfollow
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :article_id, :user_id, :index, presence: true
  validate  :belong_to_posted_article

  default_scope ->{ order index: :asc }
  scope :order_by_time, -> { reorder(nil).order created_at: :desc }

  belongs_to :user
  belongs_to :article
  belongs_to :parent, class_name: 'Comment', foreign_key: 'reply_id'

  has_many :replys, class_name: 'Comment', foreign_key: 'reply_id'
  has_many :comment_pictureships,     dependent: :destroy
  has_many :pictures,                 through: :comment_pictureships

  before_validation :set_article_in_reply, on: :create
  before_create :cal_index
  after_commit :create_notifications, on: :create

  scope :posted, ->{ where deleted_at: nil }
  scope :deleting, ->{ where.not deleted_at: nil }

  def deleted?
    return !self.deleted_at.blank?
  end

  def indexno(pre: '#', suf: 'c')
    pre + self.index.to_s + suf
  end

  private 
    # 只能在已发布文章中评论
    def belong_to_posted_article
      return unless self.article
      unless self.article.posted
        errors.add :article, I18n.t("errors.must_be_posted")
      end
    end

    # 计算评论所在层数
    # 若comments不按index正向排序
    # 则使用comments.max_by(&:index).index
    def cal_index
      return unless self.article 
      comments = self.article.comments.reload
      if comments.any?
        self.index = comments.last.index + 1
      end
    end

    # 绑定回复与上级评论的文章
    def set_article_in_reply
      @parent = parent
      self.article = @parent.article if @parent
    end

    def create_notifications
      return unless self.user
      notifications = []
      parent = self.parent

      # 回复上级评论, 通知上级评论者
      notifications << { notify_type: 'mention', user: parent.user } if parent
      # 直接评论文章, 或者回复上级评论者不是文章所有者, 则通知文章所有者
      notifications << { notify_type: 'comment', user: article.user }  if article && (parent.blank? || parent.user != article.user)

      notifications.each do |notify|
        Notification.create(
          notify_type: notify[:notify_type],
          actor: self.user,
          user: notify[:user],
          target: self)
      end
    end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_action :delete_cache_pictures, only: [:new, :edit, :index]

  def index
    case params[:by]
    when 'posted'
      @value = 2
      @comments = Comment.posted.reorder(id: :asc).paginate page: params[:page], per_page: MAX_IN_PAGE
    when 'deleting'
      @value = 3
      @comments = Comment.deleting.reorder(id: :asc).paginate page: params[:page], per_page: MAX_IN_PAGE
    else 
      @value = 1
      @comments = Comment.all.reorder(id: :asc).paginate page: params[:page], per_page: MAX_IN_PAGE
    end
  end

  def destroy
    @comment = Comment.find_by_id params[:id]
    if @comment
      @comment.destroy
      flash[:success] = I18n.t "flash.success.delete_comment", value: @comment.id
    else
      flash[:warning] = I18n.t "flash.warning.comment_not_fount", value: params[:id]
    end
    redirect_to admin_comments_path
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new comment_new_params
    _user = User.find_by_id comment_new_params[:user_id]
    unless _user
      flash.now[:warning] = I18n.t "flash.warning.user_not_fount_by_id", value: comment_new_params[:user_id]
      return render 'new'
    end

    _article = Article.find_by_id comment_new_params[:article_id]
    unless _article
      flash.now[:warning] = I18n.t "flash.warning.article_not_fount", value: comment_new_params[:article_id]
      return render 'new'
    end

    if @comment.save
      flash[:success] = I18n.t "flash.success.create"
      @comment.update_attribute :deleted_at, Time.zone.now  if params[:comment][:deleted].downcase == "true"
      redirect_to admin_comments_path
    else
      flash.now[:warning] = @comment.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
    @comment = Comment.find_by_id params[:id]
    return render_404 unless @comment
  end

  def update
    @comment = Comment.find_by_id params[:id]
    return render_404 unless @comment

    if @comment.update_attributes comment_edit_params
      deleted = params[:comment][:deleted].downcase == "true" ? Time.zone.now : ''
      @comment.update_attribute :deleted_at, deleted
      flash[:success] = I18n.t "flash.success.update"
      redirect_to admin_comments_path
    else
      flash.now[:warning] = @comment.errors.full_messages[0]
      render 'edit'
    end
  end

  private
    def comment_new_params
      params.require(:comment).permit :content, :content_html,
                                      :user_id, :article_id, :reply_id
    end

    def comment_edit_params
      params.require(:comment).permit :content, :content_html, :reply_id
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_signed_in
  before_action :check_activated
  before_action :get_user

  before_action :delete_cache_pictures, only: [:edit, :reply]
  before_action :get_comment, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def create
    @comment = @user.comments.create comment_params
    if @comment.valid?
      current_user.post_cache_pictures_in_comment @comment
      @commentsize = @comment.article.comments.where(deleted_at: nil).size
    end
  end

  def edit
    @content = @comment.content.gsub /\r\n/, '\r\n'
  end

  def reply
    @reply = Comment.select(:id, :index).find_by id: params[:id]
    render_404 unless @reply
  end

  def update
    cparams = params[:comment]
    @comment.update_attributes content: cparams[:content], content_html: cparams[:content_html]
    if @comment.valid?
      current_user.post_cache_pictures_in_comment @comment
    end
  end

  def destroy
    @comment.update_attribute :deleted_at, Time.zone.now
    @commentsize = @comment.article.comments.where(deleted_at: nil).size
  end

  private
    def comment_params
      params.require(:comment).permit(:article_id, :content, :content_html, :reply_id)
    end

    def get_user
      @user = current_user
    end

    def get_comment
      @comment = Comment.find_by id: params[:id]
      render_404 unless @comment
    end

    def correct_user
      render_404 unless current_user == @comment.user
    end

    def delete_cache_pictures
      if user = current_user
        user.delete_cache_pictures
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
  include MarkdownHelper

  # 显示评论内容
  def markdown_comment_tag(comment)
    return if comment.blank?
    comment_in_reply comment
    return sanitize_markdown comment.content_html unless comment.content_html.blank?
    markdown_content = markdown_parser.render comment.content
    sanitize_markdown markdown_content    
  end

  # 为评论添加回复父级
  def comment_in_reply(comment)
    if parent = comment.parent 
      puser = parent.user

      reply_content = '@'+puser.username+ " · " +parent.indexno(suf: '')
      comment.content = reply_content + comment.content

      reply_content_html = link_to('@'+puser.username, main_app.user_path(puser.username)) + " · " +
                      link_to(parent.indexno(suf: ''), parent.indexno)
      reply_content_html = content_tag :span, reply_content_html, class: 'reply-tag'
      comment.content_html = reply_content_html + comment.content_html.html_safe
    end
  end
end

app/views/admin/comments/_comments_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <%= content_tag :th, t("comment.content") %>
      <%= content_tag :th, t("comment.user") %>
      <%= content_tag :th, t("comment.article_id") %>
      <%= content_tag :th, t("comment.index") %>
      <%= content_tag :th, t("comment.reply_id") %>
      <%= content_tag :th, t("comment.create_time") %>
      <%= content_tag :th, t("opt") %>
    </tr>
  </thead>
  <tbody>
    <% comments.each do |comment| %>
    <tr>
      <%= content_tag :td, comment.id %>
      <%= content_tag :td, comment.content %>
      <%= content_tag :td, comment.user.username %>
      <%= content_tag :td, comment.article_id %>
      <%= content_tag :td, comment.index %>
      <%= content_tag :td, comment.reply_id %>
      <%= content_tag :td, mtime_tag(comment.created_at) %>
      <%= content_tag :td do -%>
        <%= link_to t('update'), edit_admin_comment_path(comment.id) %> /
        <%= link_to t('delete'), admin_comment_path(comment.id), value: comment.id, method: 'DELETE', id: 'to-delete' %>
      <% end -%>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/comments/edit.html.erb
<% provide :pre_title, t("comment.update") + ' | ' + t("console") %>
<% provide :bodyclass, "admin" %>
<% provide :index, '5' %>
<div id="articles">
  <div class="boxed-group">
    <%= content_tag :h3, t("comment.update") %>
    <div class="boxed-group-inner">
      <%= simple_form_for @comment, url: admin_comment_path(@comment.id) do |f| %>
      <div class="row">
        <div class="col-md-8">
          <div class="edit-body">
            <!-- 标签卡与工具栏 -->
            <div class="edit-body-header">
              <div class="post-edit-toolbar pull-right">
                <%= render 'features/markdown_toolbar' %>
              </div>
              <ul class="nav nav-tabs" id="edit-tabs">
                <%= content_tag :li, link_to(t("article.edit"), '#edit-content', class: 'edit-body-node edit-node', 'data-toggle': 'tab'), class: 'active' %>
                <%= content_tag :li, link_to(t("article.preview"), '#preview-content', class: 'edit-body-node preview-node', 'data-toggle': 'tab') %>
              </ul>
            </div>
            <!-- 编辑/预览区 -->
            <div class="tab-content edit-body-cotent" id="tab-content">
              <div class="tab-pane fade in active" id="edit-content">
                <%= f.input_field :content, as: :text, class: 'tabIndent edit-body-node edit-node', id: 'editor' %>
                <%= f.input_field :content_html, as: :hidden, id: 'content_html', disable: true %>
              </div>
              <div class="tab-pane fade" id="preview-content">
                <%= content_tag :div, '', class: 'edit-body-node preview-node standard markdown-body', id: 'previewer' %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= content_tag :span, t("comment.deleted_state") %>
            <select selected="selected" class="select form-control form-input-normal" name="comment[deleted]" id="comment_deleted">
              <%= boolean_selected_tags f.object.deleted? %>
            </select>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.user_id") %>
            <%= f.input_field :user_id, class: "form-control form-input-normal", disabled: 'disabled' %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.article_id") %>
            <%= f.input_field :article_id, class: "form-control form-input-normal", disabled: 'disabled' %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.reply_id") %>
            <%= f.input_field :reply_id, class: "form-control form-input-normal" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit t("comment.update"), class: "btn btn-primary submit", onclick: 'set_content_html()' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'editor-markdown' %>

app/views/admin/comments/index.html.erb
<% provide :pre_title, t("console-nav.comment") + ' | ' + t("console") %>
<% provide :bodyclass, "admin" %>
<% provide :index, '5' %>

<div id="users">
  <div class="boxed-group">
    <%= content_tag :h3, t("console-nav.comment") %>
    <div class="boxed-group-inner">

      <ul class="nav nav-tabs">
        <%= content_tag :li, link_to(t("c-summary.total"), admin_comments_path), class: "#{'active' if @value == 1 }" %>

        <%= content_tag :li, link_to(t("c-summary.posted"), admin_comments_path(by: 'posted')), class: "#{'active' if @value == 2 }" %>

        <%= content_tag :li, link_to(t("c-summary.deleting"), admin_comments_path(by: 'deleting')), class: "#{'active' if @value == 3 }" %>

        <%= content_tag :a, class: 'pull-right', href: new_admin_comment_path, title: t('c-summary.comment.new') do -%>
          <%= content_tag :span, '', class: 'glyphicon glyphicon-plus' %>
        <% end -%>
      </ul>

      <div id="body-content">   
        <%= render 'comments_table', comments: @comments %>
        <%= will_paginate @comments, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
      </div>

    </div>
  </div>
</div>

<%= render 'admin/features/confirm_delete_dialog' %>

<script>
  $("#body-content").on("click", "#to-delete", function(){
      text = $(this).attr("value");
      text = "<%= j t('ask.comment_delete.pre') %>" + text + "<%= j t('ask.comment_delete.suf') %>";
      $("#confirm-delete .modal-body").html(text);
      $("#confirm-delete #confirm").attr('href', $(this).attr('href'));
      $("#confirm-delete").modal();
      return false;
  });
</script>

app/views/admin/comments/new.html.erb
<% provide :pre_title, t("c-summary.comment.new") + ' | ' + t("console") %>
<% provide :bodyclass, "admin" %>
<% provide :index, '5' %>
<div id="articles">
  <div class="boxed-group">
    <%= content_tag :h3, t("c-summary.comment.new") %>
    <div class="boxed-group-inner">
      <%= simple_form_for @comment, url: admin_comments_path do |f| %>
      <div class="row">
        <div class="col-md-8">
          <div class="edit-body">
            <!-- 标签卡与工具栏 -->
            <div class="edit-body-header">
              <div class="post-edit-toolbar pull-right">
                <%= render 'features/markdown_toolbar' %>
              </div>
              <ul class="nav nav-tabs" id="edit-tabs">
                <%= content_tag :li, link_to(t("article.edit"), '#edit-content', class: 'edit-body-node edit-node', 'data-toggle': 'tab'), class: 'active' %>
                <%= content_tag :li, link_to(t("article.preview"), '#preview-content', class: 'edit-body-node preview-node', 'data-toggle': 'tab') %>
              </ul>
            </div>
            <!-- 编辑/预览区 -->
            <div class="tab-content edit-body-cotent" id="tab-content">
              <div class="tab-pane fade in active" id="edit-content">
                <%= f.input_field :content, as: :text, class: 'tabIndent edit-body-node edit-node', id: 'editor' %>
                <%= f.input_field :content_html, as: :hidden, id: 'content_html', disable: true %>
              </div>
              <div class="tab-pane fade" id="preview-content">
                <%= content_tag :div, '', class: 'edit-body-node preview-node standard markdown-body', id: 'previewer' %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= content_tag :span, t("comment.deleted_state") %>
            <select selected="selected" class="select form-control form-input-normal" name="comment[deleted]" id="comment_deleted">
              <%= boolean_selected_tags f.object.deleted? %>
            </select>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.user_id") %>
            <%= f.input_field :user_id, class: "form-control form-input-normal" %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.article_id") %>
            <%= f.input_field :article_id, class: "form-control form-input-normal" %>
          </div>

          <div class="form-group">
            <%= content_tag :span, t("comment.reply_id") %>
            <%= f.input_field :reply_id, class: "form-control form-input-normal" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit t("c-summary.comment.new"), class: "btn btn-primary submit", onclick: 'set_content_html()' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'editor-markdown' %>