config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  mount API => '/api'

  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  # 控制台
  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # 社区
  scope :community, as: 'community' do
    root 'community#index', as: 'index'
    get '/hottest' => 'community#hottest'
    get '/latest' => 'community#latest'
    get '/search' => 'search#index'
    get '/tags/:id' => 'community#tag', as: 'tag'
    get '/articles' => 'community#articles'
    get '/users' => 'community#users'
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get :blog
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#show'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
      post :follow
      post :unfollow
    end
  end

end

app/views/shared/_blog_app_header.html.erb
<%- username = @user.username %>
<%= tag :meta, name: 'current-blog', data: { username: username, title: "#{username.capitalize}'s Blog" } %>
<nav class="navbar navbar-default visible-xs app-navbar">
  <div class="container-fluid">
    <!-- 主菜单项 -->
    <div>
      <ul class="nav navbar-nav navbar-center main-nav">
        <%= content_tag :li, link_to(t("blog"), main_app.blog_user_path(username)) %>
        <%= content_tag :li, link_to(t("category"), main_app.categories_user_path(username)) %>
        <%= content_tag :li, link_to(t("archive"), main_app.archive_user_path(username)) %>
        <%= content_tag :li, link_to(t("aboutme"), main_app.aboutme_user_path(username)) %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_footer.html.erb
<footer id="footer" class="text-muted">
  <div class="container">
    <span class="site-footer-info">  © 2016 hikumho. Powered by Rails. </span>
    <span class="site-footer-links">
      <a href="https://www.github.com/hikumho">Github</a> |
      <a href="mailto:hi.jinhu.zhang@gmail.com">Email</a>
    </span>
  </div>
</footer>

app/views/shared/_blog_header.html.erb
<!-- 导航栏 -->
<nav class="navbar navbar-default hidden-xs hidden-sm">
  <div class="container-fluid">
    <!-- 导航栏首部 -->
    <div class="navbar-header">
      <!-- Logo -->
      <%= link_to image_tag("logo.png", alt:"Milog", class: "logo"), main_app.root_path, class: "navbar-brand" %>
      <!-- 切换语系 -->
      <%= link_to_locale request.path, mclass: "navbar-text switch-lang" %>

      <%= content_tag(:span, "#{capitalize_name(@user)}'s Blog", class: "navbar-text ") if current_user != @user && yield(:hidden_nav_center_items).blank? %>
      <!-- 屏幕<=420px时显示 -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- 操作菜单 -->
    <%= render 'shared/header_opt_menu' %>
    
    <!-- 主菜单项 -->
    <% if yield(:hidden_nav_center_items).blank? %>
    <div class="collapse navbar-collapse" id="collapse-nav">
      <ul class="nav navbar-nav navbar-center main-nav">
        <%= content_tag :li, link_to(t("blog"), main_app.blog_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("category"), main_app.categories_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("archive"), main_app.archive_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("aboutme"), main_app.aboutme_user_path(@user.username)) %>
        <%= content_tag :li, link_to(t("search"), "#", id: 'search') %>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

app/views/shared/_community_header.html.erb
<!-- 导航栏 -->
<nav class="navbar navbar-default hidden-xs hidden-sm">
  <div class="container-fluid">
    <!-- 导航栏首部 -->
    <div class="navbar-header">
      <!-- Logo -->
      <%= link_to image_tag("logo.png", alt:"Milog", class: "logo"), root_path, class: "navbar-brand" %>
      <!-- 切换语系 -->
      <%= link_to_locale request.path, mclass: "navbar-text switch-lang" %>

      <!-- 屏幕<=420px时显示 -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- 操作菜单 -->
    <%= render 'shared/header_opt_menu' %>
    
    <!-- 主菜单项 -->
    <div class="collapse navbar-collapse" id="collapse-nav">
      <ul class="nav navbar-nav navbar-center main-nav">
        <%= content_tag :li, link_to(t("community.home"), community_index_path) %>
        <%= content_tag :li, link_to(t("community.hottest"), community_hottest_path) %>
        <%= content_tag :li, link_to(t("community.latest"), community_latest_path) %>
        <%= content_tag :li, link_to(t("search"), '#', id: 'search') %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_flash_messages.html.erb
<% flash.each do | message_type, message | %>
  <div class="flash-alert alert alert-<%= "#{message_type}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= sanitize message %>
  </div>
<% end %>

app/views/shared/_flash_messages_inner.html.erb
<% unless flash.empty? %>
<div class="col-md-11 col-center-block content-wrap" style="width: 100%;">
  <% flash.each do | message_type, message | %>
  <div class="flash-alert-inner alert alert-<%= "#{message_type}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= sanitize message %>
  </div>
  <% end %>
</div>
<% end %>

app/views/shared/_flash_messages_jscall.html.erb
<div class="col-md-11 col-center-block content-wrap" id="flash_warning" style="display: none; width: 100%;">
  <div class="flash-alert-inner alert alert-warning">
    <a href="#" class="close" aria-label="close">&times;</a>
    <span id="message"><span>
  </div>
</div>

app/views/shared/_flash_messages_top.html.erb
<% flash.each do | message_type, message | %>
  <div class="flash-alert-top alert alert-<%= "#{message_type}" %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= sanitize message %>
  </div>
<% end %>

app/views/shared/_form_error_messages.html.erb
<% if object && object.errors.any? %>
<div class="form-error">
  <span class="form-error-field"><%= object.errors.full_messages[0] %></span>
  <span class="glyphicon glyphicon-info-sign icon"></span>
</div>
<% end %>

app/views/shared/_login_error_messages.html.erb
<% if object && object.errors.any? %>
<div class="form-error">
  <span class="form-error-field"><%= object.errors.full_messages[0] %></span>
  <span class="glyphicon glyphicon-info-sign icon"></span>
</div>
<% end %>

app/views/shared/_page_head.html.erb
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <% if signed_in? %>
    <% notify_count = Notification.unread_count(current_user) %>
    <%= tag :meta, name: "current-user", data: { username: current_user.username, email: current_user.email, avatar_url: current_user.user_avatar? ? current_user.avatar.url : current_user.letter_avatar_url(120), notify_count: notify_count} %>
  <% end %>
  <title><%= title yield(:pre_title) %></title>    
  
  <script>
    App.locale = "<%= I18n.locale %>";
  </script>
</head>

app/views/shared/_signin_form.html.erb
<!-- 登录表单 -->
<%= simple_form_for :session, url: signin_path, remote: true do |f| %>
<div class="form-error-container">
  <%= render "shared/form_error_messages", object: @user %>
</div>
<div class="form-group form-group-icon">
	<%= f.email_field :email, placeholder: t("email"), class: "form-input email" %>
	<span class="glyphicon glyphicon-envelope icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password, placeholder: t("password"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group">
	<%= f.button :submit, t("signin"), class: "btn btn-primary btn-block submit", id: "signin" %>
</div>
<div class="login-setting">
	<div class="checkbox">
		<span class="remember-me"><%= f.input_field :remember_me, as: :boolean, boolean_style: :inline %><%= t "login.remember_me" %></span>
	</div>
  <%= link_to t("login.forget_me"), accounts_passwords_forgot_path, class: "forget-me" %>
</div>
<% end %>

app/views/shared/_signup_form.html.erb
<!-- 注册表单 -->
<%= simple_form_for @user, url: signup_path, remote: true do |f| %>
<div class="form-error-container">
  <%= render "shared/form_error_messages", object: f.object %>
</div>
<div class="form-group form-group-icon">
	<%= f.input_field :username, placeholder: t("username"), class: "form-input name" %>
	<span class="glyphicon glyphicon-user icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.email_field :email, placeholder: t("email"), class: "form-input email" %>
	<span class="glyphicon glyphicon-envelope icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password, placeholder: t("password"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group form-group-icon">
	<%= f.password_field :password_confirmation, placeholder: t("password_confirmation"), class: "form-input password" %>
	<span class="glyphicon glyphicon-lock icon"></span>
</div>
<div class="form-group">
	<%= f.button :submit, t("signup"), class: "btn btn-primary btn-block submit", id: "signup" %>
</div>
<% end %>

app/views/shared/_site_footer.html.erb
<footer id="footer" class="text-muted hidden-xs hidden-sm">
  <div class="container">
    <span class="site-footer-info">  © <%= Time.now.year %> hikumho. Powered by Rails. </span>
    <span class="site-footer-links">
      <a href="https://www.github.com/hikumho">Github</a> |
      <a href="mailto:hi.jinhu.zhang@gmail.com">Email</a> |
      <a href='http://hijinhu.me/app/milog.apk'>App</a>
    </span>
  </div>
</footer>