config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  mount API => '/api'

  root 'home#index'
  
  get '/signup' => 'accounts#new'
  post '/signup' => 'accounts#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  namespace :accounts, as: 'accounts', constraints: { id: User::USERNAME_FORMAT } do
    get '/passwords/forgot' => 'passwords#new'
    post '/passwords/forgot' => 'passwords#create'

    resources :passwords, only: [:edit, :update]
    resources :activations, only: [:new, :edit] 
  end
  
  resource :account, only: [:edit] do 
    patch '/edit', action: :update
    put '/edit', action: :update
  end

  constraints( id: /\d+/ ) do
    resources :articles
    resources :categories, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      member do
        get :reply
      end
    end
  end

  # 上传图片
  match '/pictures' => 'pictures#create', via: [:post, :patch, :put]
  # 暂存文章/简历
  match '/holds' => 'holds#update', via: [:post, :patch, :put]

  # 控制台
  namespace :admin, as: 'admin' do
    root 'home#index', as: 'index'
    resources :users, except: :show
    resources :articles, except: :show
    resources :categories, except: :show
    resources :tags, except: :show
    resources :comments, except: :show
    resources :pictures, only: [:index, :destroy, :create]
  end

  # 社区
  scope :community, as: 'community' do
    root 'community#index', as: 'index'
    get '/hottest' => 'community#hottest'
    get '/latest' => 'community#latest'
    get '/search' => 'search#index'
    get '/tags/:id' => 'community#tag', as: 'tag'
    get '/articles' => 'community#articles'
    get '/users' => 'community#users'
  end

  # users相关路由最后
  resources :users, only: [:show] , path: '' , constraints: { id: User::USERNAME_FORMAT } do
    member do
      get :categories
      get :aboutme
      get :drafts
      get :archive
      get :blog
      get '/categories/:category_id', as: 'category', to: 'users#category'
      get '/tags/:tag_id', as: 'tag', to: 'users#tag'
      get '/search', to: 'search#show'
      get '/resume', to: 'resumes#show'
      match '/resume', to: 'resumes#update', via: [:patch, :put]
      get '/resume/edit', to: 'resumes#edit'
      post :follow
      post :unfollow
    end
  end

end

app/controllers/community_controller.rb
class CommunityController < ApplicationController

  before_action :get_user

  layout 'community'

  ORDER_TIME    = 0
  ORDER_VIEW    = 1
  ORDER_COMMENT = 2

  def index
    @hottest_articles = Article.hottest.order_by_time.limit 10
    @latest_articles = Article.latest.order_by_time.limit 10
    # 活跃会员 当月发文数前12位
    @users =  Article.all_during_time(Article.latest, time: :month)
                     .map{|article| article.user }.uniq
                     .sort{|user| user.articles.size}[0...12]
  end

  def hottest
    hottest_articles = Article.hottest
    hottest_articles = order hottest_articles
    @articles = hottest_articles.paginate page: params[:page], per_page: 15 unless hottest_articles.blank?
    @articles ||= []
    articles_during_time hottest_articles
    respond_to do |format|
      format.js { render :order }
      format.html 
    end
  end

  def latest
    latest_articles = Article.latest
    latest_articles = order latest_articles
    @articles = latest_articles.paginate page: params[:page], per_page: 15 unless latest_articles.blank?
    @articles ||= []
    articles_during_time latest_articles
    respond_to do |format|
      format.js { render :order }
      format.html 
    end  
  end

  def tag
    @tag = Tag.find_by_id params[:id]
    return render_404 unless @tag
    posted_articles = @tag.articles.where posted: true
    @article_size = posted_articles.size
    @articles = posted_articles.paginate page: params[:page], per_page: 15 unless posted_articles.blank?
    @articles ||= []
  end

  def articles
    articles = 
      case params[:by]
        when 'hottest_today'
          @page_title = I18n.t "community.hottest_today_pre"
          Article.all_during_time Article.hottest, time: :day
        when 'hottest_tweek'
          @page_title = I18n.t "community.hottest_tweek_pre"
          Article.all_during_time Article.hottest, time: :week
        when 'hottest_tmonth'
          @page_title = I18n.t "community.hottest_tmonth_pre"
          Article.all_during_time Article.hottest, time: :month
        when 'latest_today'
          @page_title = I18n.t "community.latest_today_pre"
          Article.all_during_time Article.latest, time: :day
        when 'latest_tweek'
          @page_title = I18n.t "community.latest_tweek_pre"
          Article.all_during_time Article.latest, time: :week
        when 'latest_tmonth'
          @page_title = I18n.t "community.latest_tmonth_pre"
          Article.all_during_time Article.latest, time: :month
        else
          @page_title = I18n.t "article.all"
          Article.where posted: true
      end      
    @article_size = articles.size
    @articles = articles.paginate page: params[:page], per_page: 15 unless articles.blank?
    @articles ||= []
  end

  def users
    users = User.abled
    @user_size = users.size
    @users = users.paginate page: params[:page], per_page: 60
  end

  private 
    def get_user
      @user = current_user if signed_in?
    end

    def order(articles)
      return [] if articles.blank?
      case params[:order]
        when 'time'
          @opt = ORDER_TIME
          articles.order_by_time
        when 'view'
          @opt = ORDER_VIEW
          articles.order_by_view_count
        when 'comment'
          @opt = ORDER_COMMENT
          articles
        else
          @opt = ORDER_TIME
          articles.order_by_time
      end
    end

    def articles_during_time(articles)
      @articles_today_size = Article.all_during_time(articles, time: :day).size 
      @articles_curweek_size = Article.all_during_time(articles, time: :week).size
      @articles_curmonth_size = Article.all_during_time(articles, time: :month).size
    end
end

app/helpers/community_helper.rb
module CommunityHelper

  def tags_tag(tags)
    return if tags.blank?
    content = tags.map { |tag| link_to '#'+tag.name, community_tag_path(tag.id) }.join ' · '
    sanitize content
  end

end

app/views/community/_articles.html.erb
<% unless articles.blank? %>
  <% articles.each do |article| %>
    <%= render 'features/article', article: article %>
  <% end %>
<% end %>

app/views/community/_articles_list.html.erb
<div class="mainer" style="margin-top: 0; padding-top: 20px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-center-block">
        <div class="boxed-group">
          <%= content_tag :h3, yield(:boxed_title) %>
          <div class="boxed-group-inner">
            <div class="post-group">
              <% articles.each do |article| %>
                <%= render 'features/article', article: article %>
              <% end %>
            </div>
          </div>
            <%= will_paginate articles, renderer: WillPaginate::ActionView::BlogLinkRenderer unless articles.blank? %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/community/articles.html.erb
<% provide :pre_title, @page_title+" | "+t("community.home") %>
<% provide :boxed_title, @page_title+" | "+(@article_size > 0 ? t("article.other", size: @article_size) : t("article.zero")) %>

<%= render 'articles_list', articles: @articles %>

app/views/community/hottest.html.erb
<% provide :pre_title, t("community.hottest") %>
<div class="mainer" style="margin-top: 0; padding-top: 20px;">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="boxed-group">
          <div class="pull-right boxed-opts" id="order-opts">
            <%= t "community.opts" %>
            <%= link_to t("community.time"), community_hottest_path(order: 'time'), remote: true, class: "#{'under-line' if @opt == CommunityController::ORDER_TIME}", 'data-order'=> 'time' %> / 
            <%= link_to t("community.view"), community_hottest_path(order: 'view'), remote: true, class: "#{'under-line' if @opt == CommunityController::ORDER_VIEW}", 'data-order'=> 'view' %> /  
            <%= link_to t("community.comment"), community_hottest_path(order: 'comment'), remote: true, class: "#{'under-line' if @opt == CommunityController::ORDER_COMMENT}", 'data-order'=> 'comment' %>         
          </div>
          <%= content_tag :h3, t("community.hottest") %>
          <div class="boxed-group-inner">
            <div class="post-group" id="post-group-content">
              <%= render 'community/articles', articles: @articles %>
            </div>
          </div>
            <div id="post-group-paginate">
              <%= will_paginate @articles, renderer: WillPaginate::ActionView::BlogLinkRenderer unless @articles.blank? %>
            </div>
        </div>
      </div>
      <div class="col-md-3 hidden-xs hidden-sm">
        <div class="boxed-group">
          <%= content_tag :h3, t("community.statistics") %>
          <div class="boxed-group-inner">
            <ul class="list-group">
              <%= content_tag :li, link_to(t("community.hottest_today", num: @articles_today_size), community_articles_path(by: :hottest_today)) %>
              <%= content_tag :li, link_to(t("community.hottest_tweek", num: @articles_curweek_size), community_articles_path(by: :hottest_tweek)) %>
              <%= content_tag :li, link_to(t("community.hottest_tmonth", num: @articles_curmonth_size), community_articles_path(by: :hottest_tmonth)) %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/community/index.html.erb
<% provide :pre_title, t("community.home") %>
<div class="mainer" style="margin-top: 0; padding-top: 20px;">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="boxed-group">
          <div class="pull-right boxed-opts">
            <%= t "community.opts" %>
            <%= link_to t("community.more"), community_hottest_path %>
          </div>
          <%= content_tag :h3, t("community.hottest") %>
          <div class="boxed-group-inner">
            <div class="post-group">
              <%= render 'community/articles', articles: @hottest_articles %>
            </div>
          </div>
        </div>

        <div class="boxed-group" style="margin-top: 40px;">
          <div class="pull-right boxed-opts">
            <%= t "community.opts" %>
            <%= link_to t("community.more"), community_latest_path %>
          </div>
          <%= content_tag :h3, t("community.latest") %>
          <div class="boxed-group-inner">
            <div class="post-group">
              <%= render 'community/articles', articles: @latest_articles %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 hidden-xs hidden-sm">
        <div class="boxed-group">
          <%= content_tag :h3, t("community.statistics") %>
          <div class="boxed-group-inner">
            <ul class="list-group">
              <%= content_tag :li, link_to(t("community.account_num", num: User.abled.size), community_users_path) %>
              <%= content_tag :li, link_to(t("community.article_num", num: Article.posted.size), community_articles_path) %>
              <%= content_tag :li, t("community.comment_num", num: Comment.posted.size) %>
            </ul>
          </div>
        </div>

        <div class="boxed-group">
          <%= content_tag :h3, t("community.active_account_tmonth") %>
          <div class="boxed-group-inner">
            <%= render 'features/users', users: @users, user_in_cols: 4 %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/community/latest.html.erb
<% provide :pre_title, t("community.latest") %>
<div class="mainer" style="margin-top: 0; padding-top: 20px;">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="boxed-group">
          <div class="pull-right boxed-opts" id="order-opts">
            <%= t "community.opts" %>
            <%= link_to t("community.time"), community_latest_path(order: 'time'), remote: true, class: "#{'under-line' if @opt == CommunityController::ORDER_TIME}", 'data-order'=> 'time' %> / 
            <%= link_to t("community.view"), community_latest_path(order: 'view'), remote: true, class: "#{'under-line' if @opt == CommunityController::ORDER_VIEW}", 'data-order'=> 'view' %> /  
            <%= link_to t("community.comment"), community_latest_path(order: 'comment') , remote: true,  class: "#{'under-line' if @opt == CommunityController::ORDER_COMMENT}", 'data-order'=> 'comment' %>         
          </div>
          <%= content_tag :h3, t("community.latest") %>
          <div class="boxed-group-inner">
            <div class="post-group" id="post-group-content">
              <%= render 'community/articles', articles: @articles %>
            </div>
          </div>
            <div id="post-group-paginate">
              <%= will_paginate @articles, renderer: WillPaginate::ActionView::BlogLinkRenderer unless @articles.blank? %>
            </div>
        </div>
      </div>
      <div class="col-md-3 hidden-xs hidden-sm">
        <div class="boxed-group">
          <%= content_tag :h3, t("community.statistics") %>
          <div class="boxed-group-inner">
            <ul class="list-group">
              <%= content_tag :li, link_to(t("community.latest_today", num: @articles_today_size), community_articles_path(by: :latest_today)) %>
              <%= content_tag :li, link_to(t("community.latest_tweek", num: @articles_curweek_size), community_articles_path(by: :latest_tweek)) %>
              <%= content_tag :li, link_to(t("community.latest_tmonth", num: @articles_curmonth_size), community_articles_path(by: :latest_tmonth)) %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/community/order.js.erb
$orderOpts = $('#order-opts');
$postGroupContent = $('#post-group-content');
$postGroupPaginate = $('#post-group-paginate');

$orderOpts.find('a.under-line').removeClass('under-line');

<% case @opt %>
<% when CommunityController::ORDER_VIEW %>
  $orderOpts.find('a[data-order=view]').addClass('under-line');
<% when CommunityController::ORDER_COMMENT %>
  $orderOpts.find('a[data-order=comment]').addClass('under-line');
<% else %>
  $orderOpts.find('a[data-order=time]').addClass('under-line');
<% end %>

$postGroupContent.html("<%=j render('community/articles', articles: @articles) %>");
$postGroupPaginate.html("<%=j will_paginate(@articles, renderer: WillPaginate::ActionView::BlogLinkRenderer) unless @articles.blank? %>");

app/views/community/tag.html.erb
<% provide :pre_title, t("article.tag")+ " : " +@tag.name+" | "+t("community.home") %>
<% provide :boxed_title, t("community.articles_in_tag", name: @tag.name, size: @article_size) %>

<%= render 'articles_list', articles: @articles %>

app/views/community/users.html.erb
<% provide :pre_title, t("community.accounts") %>

<div class="mainer" style="margin-top: 0; padding-top: 20px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-center-block">
        <div class="boxed-group">
          <%= content_tag :h3, t("community.account_num", num: @user_size) %>
          <div class="boxed-group-inner">
            <%= render 'features/users', users: @users, user_in_cols: 1 %>
          </div>
            <%= will_paginate @users, renderer: WillPaginate::ActionView::BlogLinkRenderer %>
        </div>
      </div>
    </div>
  </div>
</div>